[package]
name = "auto_impl"
version = "0.3.0"
authors = [
    "Ashley Mannix <ashleymannix@live.com.au>",
    "Lukas Kalbertodt <lukas.kalbertodt@gmail.com>",
]
license = "MIT/Apache-2.0"
description = "Automatically implement traits for common smart pointers and closures"
repository = "https://github.com/auto-impl-rs/auto_impl/"
documentation = "https://docs.rs/auto_impl/"
keywords = ["trait", "impl", "proc-macro", "closure"]
categories = ["development-tools", "rust-patterns"]
readme = "README.md"
autotests = true
edition = "2018"

[badges]
travis-ci = { repository = "auto-impl-rs/auto_impl" }


[lib]
proc-macro = true

[features]
nightly = ["proc-macro2/nightly"]

[dependencies]
proc-macro2 = { version = "1.0" }
quote = "1.0"
syn = { version = "1.0", features = ["full", "visit", "visit-mut"] }

[dev-dependencies]
build-plan = "0.1.1"
libtest-mimic = "0.1.0"

[[test]]
name = "compile-fail"
path = "tests/compile-fail.rs"
harness = false

[[test]]
name = "compile-pass"
path = "tests/compile-pass.rs"
harness = false
